# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-12 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default=b'NULL', max_length=4),
        ),
    ]
