# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-12 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
